# -*- coding: utf-8 -*-
"""Copy of draft_timestamp_it

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIOmTUmcRc8Udjn8_ag3pdf8bZe-1ih0
"""

# @title Get Video
!wget -P video/ https://ml-hiring.fringecore.sh/timestamp_it/NnNVd1JpSW5jS1VfMzYwcA_out.mp4

# @title Display Video

from IPython.display import HTML
from base64 import b64encode

mp4 = open('/content/video/NnNVd1JpSW5jS1VfMzYwcA_out.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=400 controls>
  <source src="%s" type="video/mp4">
</video>
""" % data_url)

"""# Function to Implement"""

!pip install moviepy openai-whisper --quiet

# Import libraries
import whisper
from moviepy.editor import VideoFileClip
import datetime
import difflib
def get_timestamps_for_query(video_path, query):
    from difflib import SequenceMatcher

    # Step 1: Extract audio
    audio_path = "temp_audio.mp3"
    video = VideoFileClip(video_path)
    video.audio.write_audiofile(audio_path, logger=None)

    # Step 2: Load Whisper model and transcribe
    model = whisper.load_model("base")
    result = model.transcribe(audio_path)

   # Step 3: Search for the best matching segment using fuzzy matching
    timestamp = None
    best_ratio = 0.0
    best_match = None

    for segment in result["segments"]:
        segment_text = segment["text"].lower()
        ratio = difflib.SequenceMatcher(None, query.lower(), segment_text).ratio()

        if ratio > best_ratio and ratio > 0.4:  # 0.4 threshold avoids totally irrelevant matches
            best_ratio = ratio
            best_match = segment

    if best_match:
        print(f"Best match found: '{best_match['text']}' with similarity {best_ratio:.2f}")
        timestamp = datetime.timedelta(seconds=int(best_match["start"]))
    else:
        print("No sufficiently close match found.")

    return timestamp

"""# Eval"""

# @title Eval Timestamp
video_path="/content/video/NnNVd1JpSW5jS1VfMzYwcA_out.mp4"
query="You said he wants to erode the very fabric of civilization and Soros hates humanity."
get_timestamps_for_query(video_path, query)